from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(777, 436)
        mainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(260, 0, 256, 41))
        self.textBrowser.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textBrowser.setObjectName("textBrowser")
        self.buttonActivities = QtWidgets.QPushButton(self.centralwidget)
        self.buttonActivities.setGeometry(QtCore.QRect(50, 120, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.buttonActivities.setFont(font)
        self.buttonActivities.setStyleSheet(
            "background-color: rgb(255, 0, 0);")
        self.buttonActivities.setObjectName("buttonActivities")
        self.buttonPlaces = QtWidgets.QPushButton(self.centralwidget)
        self.buttonPlaces.setGeometry(QtCore.QRect(300, 120, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.buttonPlaces.setFont(font)
        self.buttonPlaces.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.buttonPlaces.setObjectName("buttonPlaces")
        self.buttonInscriptions = QtWidgets.QPushButton(self.centralwidget)
        self.buttonInscriptions.setGeometry(QtCore.QRect(550, 120, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.buttonInscriptions.setFont(font)
        self.buttonInscriptions.setStyleSheet(
            "background-color: rgb(255, 0, 0);")
        self.buttonInscriptions.setObjectName("buttonInscriptions")
        self.buttonSchedules = QtWidgets.QPushButton(self.centralwidget)
        self.buttonSchedules.setGeometry(QtCore.QRect(50, 220, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.buttonSchedules.setFont(font)
        self.buttonSchedules.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.buttonSchedules.setObjectName("buttonSchedules")
        self.buttonEmployes = QtWidgets.QPushButton(self.centralwidget)
        self.buttonEmployes.setGeometry(QtCore.QRect(300, 220, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.buttonEmployes.setFont(font)
        self.buttonEmployes.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.buttonEmployes.setObjectName("buttonEmployes")
        self.buttonRooms = QtWidgets.QPushButton(self.centralwidget)
        self.buttonRooms.setGeometry(QtCore.QRect(550, 220, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.buttonRooms.setFont(font)
        self.buttonRooms.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.buttonRooms.setObjectName("buttonRooms")
        self.buttonPeople = QtWidgets.QPushButton(self.centralwidget)
        self.buttonPeople.setGeometry(QtCore.QRect(50, 320, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.buttonPeople.setFont(font)
        self.buttonPeople.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.buttonPeople.setObjectName("buttonPeople")
        self.buttonExit = QtWidgets.QPushButton(self.centralwidget)
        self.buttonExit.setGeometry(QtCore.QRect(550, 320, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.buttonExit.setFont(font)
        self.buttonExit.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.buttonExit.setObjectName("buttonExit")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(290, 50, 201, 31))
        self.textBrowser_2.setStyleSheet(
            "background-color: rgb(255, 255, 255);")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.buttonRegisters = QtWidgets.QPushButton(self.centralwidget)
        self.buttonRegisters.setGeometry(QtCore.QRect(300, 320, 191, 61))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.buttonRegisters.setFont(font)
        self.buttonRegisters.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.buttonRegisters.setObjectName("buttonRegisters")
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 777, 21))
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "MainWindow"))
        self.textBrowser.setHtml(_translate("mainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                            "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                            "p, li { white-space: pre-wrap; }\n"
                                            "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
                                            "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; font-weight:600; font-style:italic; text-decoration: underline;\">MENU PRINCIPAL</span></p></body></html>"))
        self.buttonActivities.setText(_translate("mainWindow", "ACTIVIDADES"))
        self.buttonPlaces.setText(_translate("mainWindow", "ALOJAMIENTOS"))
        self.buttonInscriptions.setText(
            _translate("mainWindow", "INSCRIPCIONES"))
        self.buttonSchedules.setText(_translate("mainWindow", "CRONOGRAMAS"))
        self.buttonEmployes.setText(_translate("mainWindow", "EMPLEADOS"))
        self.buttonRooms.setText(_translate("mainWindow", "HABITACIONES"))
        self.buttonPeople.setText(_translate("mainWindow", "HUESPEDES"))
        self.buttonExit.setText(_translate("mainWindow", "SALIR"))
        self.textBrowser_2.setHtml(_translate("mainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                              "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                              "p, li { white-space: pre-wrap; }\n"
                                              "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
                                              "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">Escoja una opcion</span></p></body></html>"))
        self.buttonRegisters.setText(_translate("mainWindow", "REGISTRO"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
