# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cronogramas.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(20, 20, 681, 531))
        self.frame.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.L_ActividadCronogramas = QtWidgets.QWidget(self.frame)
        self.L_ActividadCronogramas.setGeometry(QtCore.QRect(9, 10, 661, 491))
        self.L_ActividadCronogramas.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.L_ActividadCronogramas.setObjectName("L_ActividadCronogramas")
        self.widget_20 = QtWidgets.QWidget(self.L_ActividadCronogramas)
        self.widget_20.setGeometry(QtCore.QRect(0, 0, 141, 16))
        self.widget_20.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.widget_20.setObjectName("widget_20")
        self.widget_21 = QtWidgets.QWidget(self.L_ActividadCronogramas)
        self.widget_21.setGeometry(QtCore.QRect(500, 0, 161, 16))
        self.widget_21.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.widget_21.setObjectName("widget_21")
        self.widget_13 = QtWidgets.QWidget(self.L_ActividadCronogramas)
        self.widget_13.setGeometry(QtCore.QRect(0, 10, 16, 471))
        self.widget_13.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.widget_13.setObjectName("widget_13")
        self.widget_14 = QtWidgets.QWidget(self.L_ActividadCronogramas)
        self.widget_14.setGeometry(QtCore.QRect(0, 480, 661, 20))
        self.widget_14.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.widget_14.setObjectName("widget_14")
        self.widget_15 = QtWidgets.QWidget(self.L_ActividadCronogramas)
        self.widget_15.setGeometry(QtCore.QRect(648, 10, 16, 471))
        self.widget_15.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.widget_15.setObjectName("widget_15")
        self.label_25 = QtWidgets.QLabel(self.L_ActividadCronogramas)
        self.label_25.setGeometry(QtCore.QRect(220, 60, 201, 20))
        self.label_25.setStyleSheet("border-color: rgb(255, 0, 0);\n"
"background-color: rgb(85, 255, 0);\n"
"background-color: rgb(85, 255, 0);")
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.L_ActividadCronogramas)
        self.label_26.setGeometry(QtCore.QRect(150, 250, 361, 20))
        self.label_26.setStyleSheet("background-color: rgb(255, 0, 127);\n"
"background-color: rgb(85, 255, 0);")
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.L_ActividadCronogramas)
        self.label_27.setGeometry(QtCore.QRect(20, 280, 61, 20))
        self.label_27.setObjectName("label_27")
        self.L_ActividadCronogramas2 = QtWidgets.QLineEdit(self.L_ActividadCronogramas)
        self.L_ActividadCronogramas2.setGeometry(QtCore.QRect(80, 280, 113, 20))
        self.L_ActividadCronogramas2.setObjectName("L_ActividadCronogramas2")
        self.BbuscarCronogramas = QtWidgets.QPushButton(self.L_ActividadCronogramas)
        self.BbuscarCronogramas.setGeometry(QtCore.QRect(220, 280, 81, 21))
        self.BbuscarCronogramas.setStyleSheet("background-color: rgb(255, 0, 127);\n"
"background-color: rgb(85, 255, 0);")
        self.BbuscarCronogramas.setObjectName("BbuscarCronogramas")
        self.BeliminarCronogramas = QtWidgets.QPushButton(self.L_ActividadCronogramas)
        self.BeliminarCronogramas.setGeometry(QtCore.QRect(340, 280, 75, 23))
        self.BeliminarCronogramas.setStyleSheet("background-color: rgb(255, 0, 127);\n"
"background-color: rgb(85, 255, 0);")
        self.BeliminarCronogramas.setObjectName("BeliminarCronogramas")
        self.BmodificarCronogramas = QtWidgets.QPushButton(self.L_ActividadCronogramas)
        self.BmodificarCronogramas.setGeometry(QtCore.QRect(470, 280, 75, 23))
        self.BmodificarCronogramas.setStyleSheet("background-color: rgb(255, 0, 127);\n"
"background-color: rgb(85, 255, 0);")
        self.BmodificarCronogramas.setObjectName("BmodificarCronogramas")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.L_ActividadCronogramas)
        self.textBrowser_2.setGeometry(QtCore.QRect(140, 0, 361, 61))
        self.textBrowser_2.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.label_39 = QtWidgets.QLabel(self.L_ActividadCronogramas)
        self.label_39.setGeometry(QtCore.QRect(60, 110, 61, 16))
        self.label_39.setObjectName("label_39")
        self.L_ActividadCronograma = QtWidgets.QLineEdit(self.L_ActividadCronogramas)
        self.L_ActividadCronograma.setGeometry(QtCore.QRect(60, 130, 151, 31))
        self.L_ActividadCronograma.setObjectName("L_ActividadCronograma")
        self.label_40 = QtWidgets.QLabel(self.L_ActividadCronogramas)
        self.label_40.setGeometry(QtCore.QRect(270, 110, 91, 16))
        self.label_40.setObjectName("label_40")
        self.L_AlojamientoCronograma = QtWidgets.QLineEdit(self.L_ActividadCronogramas)
        self.L_AlojamientoCronograma.setGeometry(QtCore.QRect(260, 130, 151, 31))
        self.L_AlojamientoCronograma.setObjectName("L_AlojamientoCronograma")
        self.label_41 = QtWidgets.QLabel(self.L_ActividadCronogramas)
        self.label_41.setGeometry(QtCore.QRect(60, 180, 47, 13))
        self.label_41.setObjectName("label_41")
        self.L_DiaCronogramas = QtWidgets.QLineEdit(self.L_ActividadCronogramas)
        self.L_DiaCronogramas.setGeometry(QtCore.QRect(60, 200, 151, 31))
        self.L_DiaCronogramas.setObjectName("L_DiaCronogramas")
        self.label_42 = QtWidgets.QLabel(self.L_ActividadCronogramas)
        self.label_42.setGeometry(QtCore.QRect(260, 180, 47, 13))
        self.label_42.setObjectName("label_42")
        self.L_HoraCronograma = QtWidgets.QLineEdit(self.L_ActividadCronogramas)
        self.L_HoraCronograma.setGeometry(QtCore.QRect(260, 200, 151, 31))
        self.L_HoraCronograma.setObjectName("L_HoraCronograma")
        self.BagregarCronogramas = QtWidgets.QPushButton(self.L_ActividadCronogramas)
        self.BagregarCronogramas.setGeometry(QtCore.QRect(560, 250, 75, 23))
        self.BagregarCronogramas.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.BagregarCronogramas.setObjectName("BagregarCronogramas")
        self.T_Cronogramas = QtWidgets.QTreeWidget(self.L_ActividadCronogramas)
        self.T_Cronogramas.setGeometry(QtCore.QRect(20, 310, 621, 161))
        self.T_Cronogramas.setObjectName("T_Cronogramas")
        self.BSalirCrongramas = QtWidgets.QPushButton(self.L_ActividadCronogramas)
        self.BSalirCrongramas.setGeometry(QtCore.QRect(30, 50, 75, 23))
        self.BSalirCrongramas.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.BSalirCrongramas.setObjectName("BSalirCrongramas")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_25.setText(_translate("MainWindow", "INGRESE LA SIGUIENTE INFORMACION:"))
        self.label_26.setText(_translate("MainWindow", "INGRESE EL ID PARA BUSCAR,ELIMINAR O MODIFICAR"))
        self.label_27.setText(_translate("MainWindow", "ACTIVIDAD:"))
        self.BbuscarCronogramas.setText(_translate("MainWindow", "BUSCAR"))
        self.BeliminarCronogramas.setText(_translate("MainWindow", "ELIMINAR"))
        self.BmodificarCronogramas.setText(_translate("MainWindow", "MODIFICAR"))
        self.textBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; font-weight:600; font-style:italic; text-decoration: underline; color:#00ff00;\">MENU </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; font-weight:600; font-style:italic; text-decoration: underline; color:#00ff00;\">CRONOGRAMAS</span></p></body></html>"))
        self.label_39.setText(_translate("MainWindow", "ACTIVIDAD:"))
        self.label_40.setText(_translate("MainWindow", "ALOJAMIENTO:"))
        self.label_41.setText(_translate("MainWindow", "DIA:"))
        self.label_42.setText(_translate("MainWindow", "HORA:"))
        self.BagregarCronogramas.setText(_translate("MainWindow", "AGREGAR"))
        self.T_Cronogramas.headerItem().setText(0, _translate("MainWindow", "ACTIVIDAD:"))
        self.T_Cronogramas.headerItem().setText(1, _translate("MainWindow", "ALOJAMIENTO:"))
        self.T_Cronogramas.headerItem().setText(2, _translate("MainWindow", "DIA"))
        self.T_Cronogramas.headerItem().setText(3, _translate("MainWindow", "HORA"))
        self.BSalirCrongramas.setText(_translate("MainWindow", "SALIR:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
