# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inscripciones.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget_4 = QtWidgets.QWidget(self.centralwidget)
        self.widget_4.setGeometry(QtCore.QRect(0, 0, 681, 531))
        self.widget_4.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"alternate-background-color: rgb(255, 0, 0);")
        self.widget_4.setObjectName("widget_4")
        self.widget_7 = QtWidgets.QWidget(self.widget_4)
        self.widget_7.setGeometry(QtCore.QRect(8, 10, 661, 481))
        self.widget_7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_7.setObjectName("widget_7")
        self.textBrowser_7 = QtWidgets.QTextBrowser(self.widget_7)
        self.textBrowser_7.setGeometry(QtCore.QRect(220, -2, 256, 71))
        self.textBrowser_7.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.textBrowser_7.setObjectName("textBrowser_7")
        self.widget_38 = QtWidgets.QWidget(self.widget_7)
        self.widget_38.setGeometry(QtCore.QRect(0, 0, 221, 16))
        self.widget_38.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.widget_38.setObjectName("widget_38")
        self.widget_39 = QtWidgets.QWidget(self.widget_7)
        self.widget_39.setGeometry(QtCore.QRect(0, 10, 16, 461))
        self.widget_39.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.widget_39.setObjectName("widget_39")
        self.widget_41 = QtWidgets.QWidget(self.widget_7)
        self.widget_41.setGeometry(QtCore.QRect(645, 0, 16, 471))
        self.widget_41.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.widget_41.setObjectName("widget_41")
        self.widget_42 = QtWidgets.QWidget(self.widget_7)
        self.widget_42.setGeometry(QtCore.QRect(470, 0, 181, 16))
        self.widget_42.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.widget_42.setObjectName("widget_42")
        self.widget_40 = QtWidgets.QWidget(self.widget_7)
        self.widget_40.setGeometry(QtCore.QRect(0, 470, 661, 20))
        self.widget_40.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.widget_40.setObjectName("widget_40")
        self.label_10 = QtWidgets.QLabel(self.widget_7)
        self.label_10.setGeometry(QtCore.QRect(180, 190, 361, 20))
        self.label_10.setStyleSheet("background-color: rgb(255, 0, 127);\n"
"background-color: rgb(255, 85, 0);")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.widget_7)
        self.label_11.setGeometry(QtCore.QRect(20, 220, 61, 16))
        self.label_11.setObjectName("label_11")
        self.L_ActividadInscripcione2 = QtWidgets.QLineEdit(self.widget_7)
        self.L_ActividadInscripcione2.setGeometry(QtCore.QRect(100, 220, 113, 20))
        self.L_ActividadInscripcione2.setObjectName("L_ActividadInscripcione2")
        self.BbuscarInscripciones = QtWidgets.QPushButton(self.widget_7)
        self.BbuscarInscripciones.setGeometry(QtCore.QRect(230, 220, 81, 21))
        self.BbuscarInscripciones.setStyleSheet("background-color: rgb(255, 0, 127);\n"
"background-color: rgb(255, 85, 0);")
        self.BbuscarInscripciones.setObjectName("BbuscarInscripciones")
        self.BeliminarInscripciones = QtWidgets.QPushButton(self.widget_7)
        self.BeliminarInscripciones.setGeometry(QtCore.QRect(370, 220, 75, 23))
        self.BeliminarInscripciones.setStyleSheet("background-color: rgb(255, 0, 127);\n"
"background-color: rgb(255, 85, 0);")
        self.BeliminarInscripciones.setObjectName("BeliminarInscripciones")
        self.BmodificarInscripciones = QtWidgets.QPushButton(self.widget_7)
        self.BmodificarInscripciones.setGeometry(QtCore.QRect(520, 220, 75, 23))
        self.BmodificarInscripciones.setStyleSheet("background-color: rgb(255, 0, 127);\n"
"background-color: rgb(255, 85, 0);")
        self.BmodificarInscripciones.setObjectName("BmodificarInscripciones")
        self.label_12 = QtWidgets.QLabel(self.widget_7)
        self.label_12.setGeometry(QtCore.QRect(240, 70, 211, 20))
        self.label_12.setStyleSheet("border-color: rgb(255, 0, 0);\n"
"background-color: rgb(255, 85, 0);\n"
"background-color: rgb(255, 85, 0);")
        self.label_12.setObjectName("label_12")
        self.label_60 = QtWidgets.QLabel(self.widget_7)
        self.label_60.setGeometry(QtCore.QRect(50, 120, 71, 16))
        self.label_60.setObjectName("label_60")
        self.L_ActividadInscripciones = QtWidgets.QLineEdit(self.widget_7)
        self.L_ActividadInscripciones.setGeometry(QtCore.QRect(40, 140, 151, 31))
        self.L_ActividadInscripciones.setObjectName("L_ActividadInscripciones")
        self.label_61 = QtWidgets.QLabel(self.widget_7)
        self.label_61.setGeometry(QtCore.QRect(270, 120, 91, 16))
        self.label_61.setObjectName("label_61")
        self.L_AlojamientoInscripciones = QtWidgets.QLineEdit(self.widget_7)
        self.L_AlojamientoInscripciones.setGeometry(QtCore.QRect(260, 140, 171, 31))
        self.L_AlojamientoInscripciones.setObjectName("L_AlojamientoInscripciones")
        self.label_62 = QtWidgets.QLabel(self.widget_7)
        self.label_62.setGeometry(QtCore.QRect(490, 120, 47, 13))
        self.label_62.setObjectName("label_62")
        self.L_HuespedInscripcion = QtWidgets.QLineEdit(self.widget_7)
        self.L_HuespedInscripcion.setGeometry(QtCore.QRect(480, 140, 161, 31))
        self.L_HuespedInscripcion.setObjectName("L_HuespedInscripcion")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget_7)
        self.pushButton_2.setGeometry(QtCore.QRect(560, 190, 75, 23))
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 85, 0);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.T_Inscripciones = QtWidgets.QTreeWidget(self.widget_7)
        self.T_Inscripciones.setGeometry(QtCore.QRect(20, 250, 611, 192))
        self.T_Inscripciones.setObjectName("T_Inscripciones")
        self.BSalirInscripciones = QtWidgets.QPushButton(self.widget_7)
        self.BSalirInscripciones.setGeometry(QtCore.QRect(60, 50, 75, 23))
        self.BSalirInscripciones.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.BSalirInscripciones.setObjectName("BSalirInscripciones")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textBrowser_7.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; font-weight:600; font-style:italic; text-decoration: underline; color:#ff5500;\">MENU </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; font-weight:600; font-style:italic; text-decoration: underline; color:#ff5500;\">INSCRIPCIONES</span></p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "INGRESE EL ID PARA BUSCAR,ELIMINAR O MODIFICAR"))
        self.label_11.setText(_translate("MainWindow", "ACTIVIDAD:"))
        self.BbuscarInscripciones.setText(_translate("MainWindow", "BUSCAR"))
        self.BeliminarInscripciones.setText(_translate("MainWindow", "ELIMINAR"))
        self.BmodificarInscripciones.setText(_translate("MainWindow", "MODIFICAR"))
        self.label_12.setText(_translate("MainWindow", "INGRESE LA SIGUIENTE INFORMACION :"))
        self.label_60.setText(_translate("MainWindow", "ACTIVIDAD:"))
        self.label_61.setText(_translate("MainWindow", "ALOJAMIENTO:"))
        self.label_62.setText(_translate("MainWindow", "HUESPED:"))
        self.pushButton_2.setText(_translate("MainWindow", "AGREGAR"))
        self.T_Inscripciones.headerItem().setText(0, _translate("MainWindow", "ACTIVIDAD:"))
        self.T_Inscripciones.headerItem().setText(1, _translate("MainWindow", "ALOJAMIENTO:"))
        self.T_Inscripciones.headerItem().setText(2, _translate("MainWindow", "HUESPED:"))
        self.BSalirInscripciones.setText(_translate("MainWindow", "SALIR:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
