# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(777, 436)
        mainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(260, 0, 256, 41))
        self.textBrowser.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textBrowser.setObjectName("textBrowser")
        self.Bactividades = QtWidgets.QPushButton(self.centralwidget)
        self.Bactividades.setGeometry(QtCore.QRect(50, 120, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Bactividades.setFont(font)
        self.Bactividades.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.Bactividades.setObjectName("Bactividades")
        self.Balojamientos = QtWidgets.QPushButton(self.centralwidget)
        self.Balojamientos.setGeometry(QtCore.QRect(300, 120, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Balojamientos.setFont(font)
        self.Balojamientos.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.Balojamientos.setObjectName("Balojamientos")
        self.Binscripciones = QtWidgets.QPushButton(self.centralwidget)
        self.Binscripciones.setGeometry(QtCore.QRect(550, 120, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Binscripciones.setFont(font)
        self.Binscripciones.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.Binscripciones.setObjectName("Binscripciones")
        self.Bcronogramas = QtWidgets.QPushButton(self.centralwidget)
        self.Bcronogramas.setGeometry(QtCore.QRect(50, 220, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Bcronogramas.setFont(font)
        self.Bcronogramas.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.Bcronogramas.setObjectName("Bcronogramas")
        self.Bempleados = QtWidgets.QPushButton(self.centralwidget)
        self.Bempleados.setGeometry(QtCore.QRect(300, 220, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Bempleados.setFont(font)
        self.Bempleados.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.Bempleados.setObjectName("Bempleados")
        self.Bhabitaciones = QtWidgets.QPushButton(self.centralwidget)
        self.Bhabitaciones.setGeometry(QtCore.QRect(550, 220, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Bhabitaciones.setFont(font)
        self.Bhabitaciones.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.Bhabitaciones.setObjectName("Bhabitaciones")
        self.Bhuespedes = QtWidgets.QPushButton(self.centralwidget)
        self.Bhuespedes.setGeometry(QtCore.QRect(50, 320, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Bhuespedes.setFont(font)
        self.Bhuespedes.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.Bhuespedes.setObjectName("Bhuespedes")
        self.BSalir = QtWidgets.QPushButton(self.centralwidget)
        self.BSalir.setGeometry(QtCore.QRect(550, 320, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.BSalir.setFont(font)
        self.BSalir.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.BSalir.setObjectName("BSalir")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(290, 50, 201, 31))
        self.textBrowser_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.Bregistro = QtWidgets.QPushButton(self.centralwidget)
        self.Bregistro.setGeometry(QtCore.QRect(300, 320, 191, 61))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Bregistro.setFont(font)
        self.Bregistro.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.Bregistro.setObjectName("Bregistro")
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 777, 21))
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "MainWindow"))
        self.textBrowser.setHtml(_translate("mainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; font-weight:600; font-style:italic; text-decoration: underline;\">MENU PRINCIPAL</span></p></body></html>"))
        self.Bactividades.setText(_translate("mainWindow", "ACTIVIDADES"))
        self.Balojamientos.setText(_translate("mainWindow", "ALOJAMIENTOS"))
        self.Binscripciones.setText(_translate("mainWindow", "INSCRIPCIONES"))
        self.Bcronogramas.setText(_translate("mainWindow", "CRONOGRAMAS"))
        self.Bempleados.setText(_translate("mainWindow", "EMPLEADOS"))
        self.Bhabitaciones.setText(_translate("mainWindow", "HABITACIONES"))
        self.Bhuespedes.setText(_translate("mainWindow", "HUESPEDES"))
        self.BSalir.setText(_translate("mainWindow", "SALIR"))
        self.textBrowser_2.setHtml(_translate("mainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">Escoja una opcion</span></p></body></html>"))
        self.Bregistro.setText(_translate("mainWindow", "REGISTRO"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
