# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'registro.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget_47 = QtWidgets.QWidget(self.centralwidget)
        self.widget_47.setGeometry(QtCore.QRect(10, 0, 681, 531))
        self.widget_47.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"background-color: rgb(170, 85, 255);\n"
"background-color: rgb(170, 85, 255);")
        self.widget_47.setObjectName("widget_47")
        self.widget_48 = QtWidgets.QWidget(self.widget_47)
        self.widget_48.setGeometry(QtCore.QRect(8, 10, 661, 481))
        self.widget_48.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_48.setObjectName("widget_48")
        self.textBrowser_9 = QtWidgets.QTextBrowser(self.widget_48)
        self.textBrowser_9.setGeometry(QtCore.QRect(220, -2, 256, 71))
        self.textBrowser_9.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.textBrowser_9.setObjectName("textBrowser_9")
        self.widget_49 = QtWidgets.QWidget(self.widget_48)
        self.widget_49.setGeometry(QtCore.QRect(0, 0, 221, 16))
        self.widget_49.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.widget_49.setObjectName("widget_49")
        self.widget_50 = QtWidgets.QWidget(self.widget_48)
        self.widget_50.setGeometry(QtCore.QRect(0, 10, 16, 461))
        self.widget_50.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.widget_50.setObjectName("widget_50")
        self.widget_51 = QtWidgets.QWidget(self.widget_48)
        self.widget_51.setGeometry(QtCore.QRect(645, 0, 16, 471))
        self.widget_51.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.widget_51.setObjectName("widget_51")
        self.widget_52 = QtWidgets.QWidget(self.widget_48)
        self.widget_52.setGeometry(QtCore.QRect(470, 0, 181, 16))
        self.widget_52.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.widget_52.setObjectName("widget_52")
        self.widget_53 = QtWidgets.QWidget(self.widget_48)
        self.widget_53.setGeometry(QtCore.QRect(0, 470, 661, 20))
        self.widget_53.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.widget_53.setObjectName("widget_53")
        self.label_31 = QtWidgets.QLabel(self.widget_48)
        self.label_31.setGeometry(QtCore.QRect(170, 250, 361, 20))
        self.label_31.setStyleSheet("background-color: rgb(255, 0, 127);\n"
"background-color: rgb(0, 85, 0);\n"
"background-color: rgb(170, 85, 255);")
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.widget_48)
        self.label_32.setGeometry(QtCore.QRect(30, 280, 51, 16))
        self.label_32.setObjectName("label_32")
        self.L_HuespedRegistro2 = QtWidgets.QLineEdit(self.widget_48)
        self.L_HuespedRegistro2.setGeometry(QtCore.QRect(110, 280, 113, 20))
        self.L_HuespedRegistro2.setObjectName("L_HuespedRegistro2")
        self.BbuscarRegistro = QtWidgets.QPushButton(self.widget_48)
        self.BbuscarRegistro.setGeometry(QtCore.QRect(250, 280, 81, 21))
        self.BbuscarRegistro.setStyleSheet("background-color: rgb(255, 0, 127);\n"
"background-color: rgb(0, 85, 0);\n"
"background-color: rgb(170, 85, 255);")
        self.BbuscarRegistro.setObjectName("BbuscarRegistro")
        self.BeliminarRegistro = QtWidgets.QPushButton(self.widget_48)
        self.BeliminarRegistro.setGeometry(QtCore.QRect(370, 280, 75, 23))
        self.BeliminarRegistro.setStyleSheet("background-color: rgb(255, 0, 127);\n"
"background-color: rgb(0, 85, 0);\n"
"background-color: rgb(170, 85, 255);")
        self.BeliminarRegistro.setObjectName("BeliminarRegistro")
        self.BmodificarRegistro = QtWidgets.QPushButton(self.widget_48)
        self.BmodificarRegistro.setGeometry(QtCore.QRect(480, 280, 75, 23))
        self.BmodificarRegistro.setStyleSheet("background-color: rgb(255, 0, 127);\n"
"background-color: rgb(255, 255, 127);\n"
"background-color: rgb(170, 85, 255);")
        self.BmodificarRegistro.setObjectName("BmodificarRegistro")
        self.label_33 = QtWidgets.QLabel(self.widget_48)
        self.label_33.setGeometry(QtCore.QRect(250, 70, 201, 20))
        self.label_33.setStyleSheet("border-color: rgb(255, 0, 0);\n"
"background-color: rgb(0, 85, 0);\n"
"background-color: rgb(170, 85, 255);")
        self.label_33.setObjectName("label_33")
        self.label_63 = QtWidgets.QLabel(self.widget_48)
        self.label_63.setGeometry(QtCore.QRect(40, 120, 61, 16))
        self.label_63.setObjectName("label_63")
        self.L_HuespedRegistr = QtWidgets.QLineEdit(self.widget_48)
        self.L_HuespedRegistr.setGeometry(QtCore.QRect(30, 140, 161, 31))
        self.L_HuespedRegistr.setObjectName("L_HuespedRegistr")
        self.label_64 = QtWidgets.QLabel(self.widget_48)
        self.label_64.setGeometry(QtCore.QRect(240, 120, 81, 16))
        self.label_64.setObjectName("label_64")
        self.L_HabitacionHuesped = QtWidgets.QLineEdit(self.widget_48)
        self.L_HabitacionHuesped.setGeometry(QtCore.QRect(230, 140, 181, 31))
        self.L_HabitacionHuesped.setObjectName("L_HabitacionHuesped")
        self.label_65 = QtWidgets.QLabel(self.widget_48)
        self.label_65.setGeometry(QtCore.QRect(460, 120, 101, 16))
        self.label_65.setObjectName("label_65")
        self.L_FechainRegistro = QtWidgets.QLineEdit(self.widget_48)
        self.L_FechainRegistro.setGeometry(QtCore.QRect(450, 140, 151, 31))
        self.L_FechainRegistro.setObjectName("L_FechainRegistro")
        self.label_66 = QtWidgets.QLabel(self.widget_48)
        self.label_66.setGeometry(QtCore.QRect(40, 190, 101, 16))
        self.label_66.setObjectName("label_66")
        self.L_FechaoutRegistro = QtWidgets.QLineEdit(self.widget_48)
        self.L_FechaoutRegistro.setGeometry(QtCore.QRect(30, 210, 161, 31))
        self.L_FechaoutRegistro.setObjectName("L_FechaoutRegistro")
        self.label_67 = QtWidgets.QLabel(self.widget_48)
        self.label_67.setGeometry(QtCore.QRect(240, 190, 47, 13))
        self.label_67.setObjectName("label_67")
        self.L_CuentaRegistro = QtWidgets.QLineEdit(self.widget_48)
        self.L_CuentaRegistro.setGeometry(QtCore.QRect(230, 210, 181, 31))
        self.L_CuentaRegistro.setObjectName("L_CuentaRegistro")
        self.pushButton_5 = QtWidgets.QPushButton(self.widget_48)
        self.pushButton_5.setGeometry(QtCore.QRect(560, 250, 75, 23))
        self.pushButton_5.setStyleSheet("background-color: rgb(170, 0, 255);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.T_Registro = QtWidgets.QTreeWidget(self.widget_48)
        self.T_Registro.setGeometry(QtCore.QRect(30, 320, 611, 151))
        self.T_Registro.setObjectName("T_Registro")
        self.BSalirRegistro = QtWidgets.QPushButton(self.widget_48)
        self.BSalirRegistro.setGeometry(QtCore.QRect(50, 50, 75, 23))
        self.BSalirRegistro.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.BSalirRegistro.setObjectName("BSalirRegistro")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textBrowser_9.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; font-weight:600; font-style:italic; text-decoration: underline; color:#aa00ff;\">MENU </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; font-weight:600; font-style:italic; text-decoration: underline; color:#aa00ff;\">REGISTRO</span></p></body></html>"))
        self.label_31.setText(_translate("MainWindow", "INGRESE EL ID PARA BUSCAR,ELIMINAR O MODIFICAR"))
        self.label_32.setText(_translate("MainWindow", "HUESPED:"))
        self.BbuscarRegistro.setText(_translate("MainWindow", "BUSCAR"))
        self.BeliminarRegistro.setText(_translate("MainWindow", "ELIMINAR"))
        self.BmodificarRegistro.setText(_translate("MainWindow", "MODIFICAR"))
        self.label_33.setText(_translate("MainWindow", "INGRESE LA SIGUIENTE INFORMACION:"))
        self.label_63.setText(_translate("MainWindow", "HUESPED:"))
        self.label_64.setText(_translate("MainWindow", "HABITACION:"))
        self.label_65.setText(_translate("MainWindow", "FECHA DE ENTRADA:"))
        self.label_66.setText(_translate("MainWindow", "FECHA DE SALIDA:"))
        self.label_67.setText(_translate("MainWindow", "CUENTA:"))
        self.pushButton_5.setText(_translate("MainWindow", "AGREGAR"))
        self.T_Registro.headerItem().setText(0, _translate("MainWindow", "HUESPED:"))
        self.T_Registro.headerItem().setText(1, _translate("MainWindow", "HABITACION:"))
        self.T_Registro.headerItem().setText(2, _translate("MainWindow", "FE DE ENTRADA:"))
        self.T_Registro.headerItem().setText(3, _translate("MainWindow", "FE DE SALIDA:"))
        self.T_Registro.headerItem().setText(4, _translate("MainWindow", "CUENTA:"))
        self.BSalirRegistro.setText(_translate("MainWindow", "SALIR:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
